# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'convertGerbers_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1024, 440)
        Dialog.setStyleSheet("QLabel > lblConvertGerbers{\n"
"\n"
"border: 4px dashed #aaa;\n"
"\n"
"}")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1001, 101))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblConvertGerbers = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblConvertGerbers.setFont(font)
        self.lblConvertGerbers.setStyleSheet("QLabel {\n"
"    border: 4px dashed #aaa\n"
" }")
        self.lblConvertGerbers.setAlignment(QtCore.Qt.AlignCenter)
        self.lblConvertGerbers.setObjectName("lblConvertGerbers")
        self.horizontalLayout.addWidget(self.lblConvertGerbers)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 110, 1001, 71))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ledGerberPath = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.ledGerberPath.setObjectName("ledGerberPath")
        self.horizontalLayout_2.addWidget(self.ledGerberPath)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnImportGrbs = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnImportGrbs.setFont(font)
        self.btnImportGrbs.setStyleSheet("padding: 10px")
        self.btnImportGrbs.setObjectName("btnImportGrbs")
        self.horizontalLayout_2.addWidget(self.btnImportGrbs)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 360, 1001, 61))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btnRenameGerbers = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnRenameGerbers.setFont(font)
        self.btnRenameGerbers.setObjectName("btnRenameGerbers")
        self.horizontalLayout_3.addWidget(self.btnRenameGerbers)
        spacerItem3 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 180, 1001, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblConvertGerbersDisplayChanges = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblConvertGerbersDisplayChanges.setFont(font)
        self.lblConvertGerbersDisplayChanges.setAlignment(QtCore.Qt.AlignCenter)
        self.lblConvertGerbersDisplayChanges.setObjectName("lblConvertGerbersDisplayChanges")
        self.verticalLayout.addWidget(self.lblConvertGerbersDisplayChanges)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblConvertGerbers.setText(_translate("Dialog", "<html><head/><body><p>Drag and drop </p><p>compressed gerber files here</p></body></html>"))
        self.btnImportGrbs.setText(_translate("Dialog", "Click here to import"))
        self.btnRenameGerbers.setText(_translate("Dialog", "Rename\n"
"Layers"))
        self.lblConvertGerbersDisplayChanges.setText(_translate("Dialog", "No gerbers were imported yet...."))
