# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GenerateNeodenFile_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1024, 440)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 80, 491, 201))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblGenrateNeodenGerbers = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblGenrateNeodenGerbers.setFont(font)
        self.lblGenrateNeodenGerbers.setStyleSheet("QLabel {\n"
"    border: 4px dashed #aaa\n"
" }")
        self.lblGenrateNeodenGerbers.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGenrateNeodenGerbers.setObjectName("lblGenrateNeodenGerbers")
        self.horizontalLayout.addWidget(self.lblGenrateNeodenGerbers)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(520, 80, 491, 201))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblGenerateNeodenLoadPos = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblGenerateNeodenLoadPos.setFont(font)
        self.lblGenerateNeodenLoadPos.setStyleSheet("QLabel {\n"
"    border: 4px dashed #aaa\n"
" }")
        self.lblGenerateNeodenLoadPos.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGenerateNeodenLoadPos.setObjectName("lblGenerateNeodenLoadPos")
        self.horizontalLayout_2.addWidget(self.lblGenerateNeodenLoadPos)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 279, 491, 81))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnGenerateNeodenLoadGerbers = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnGenerateNeodenLoadGerbers.setFont(font)
        self.btnGenerateNeodenLoadGerbers.setObjectName("btnGenerateNeodenLoadGerbers")
        self.horizontalLayout_3.addWidget(self.btnGenerateNeodenLoadGerbers)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(520, 280, 491, 81))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnGenerateNeodenLoadPos = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnGenerateNeodenLoadPos.setFont(font)
        self.btnGenerateNeodenLoadPos.setObjectName("btnGenerateNeodenLoadPos")
        self.horizontalLayout_4.addWidget(self.btnGenerateNeodenLoadPos)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblGenrateNeodenGerbers.setText(_translate("Dialog", "Drag and drop\n"
"gerber files"))
        self.lblGenerateNeodenLoadPos.setText(_translate("Dialog", "Drag and drop\n"
"component position file"))
        self.btnGenerateNeodenLoadGerbers.setText(_translate("Dialog", "Load \n"
"gerber files"))
        self.btnGenerateNeodenLoadPos.setText(_translate("Dialog", "Load\n"
"position file"))
