# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowDialog(object):
    def setupUi(self, MainWindowDialog):
        MainWindowDialog.setObjectName("MainWindowDialog")
        MainWindowDialog.setWindowModality(QtCore.Qt.NonModal)
        MainWindowDialog.resize(457, 147)
        MainWindowDialog.setMinimumSize(QtCore.QSize(457, 147))
        MainWindowDialog.setMaximumSize(QtCore.QSize(99999, 99999))
        MainWindowDialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindowDialog.setSizeGripEnabled(True)
        self.verticalLayoutWidget = QtWidgets.QWidget(MainWindowDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 461, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vQBox_main = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vQBox_main.setContentsMargins(0, 0, 0, 0)
        self.vQBox_main.setObjectName("vQBox_main")
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.vQBox_main.addItem(spacerItem)
        self.hQbox_1 = QtWidgets.QHBoxLayout()
        self.hQbox_1.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.hQbox_1.setObjectName("hQbox_1")
        spacerItem1 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.hQbox_1.addItem(spacerItem1)
        self.btnConvertGrb = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnConvertGrb.setMinimumSize(QtCore.QSize(207, 77))
        self.btnConvertGrb.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnConvertGrb.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnConvertGrb.setFont(font)
        self.btnConvertGrb.setObjectName("btnConvertGrb")
        self.hQbox_1.addWidget(self.btnConvertGrb)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hQbox_1.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.hQbox_1.addItem(spacerItem3)
        self.btnGenerateNeodenFile = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnGenerateNeodenFile.setMinimumSize(QtCore.QSize(184, 77))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnGenerateNeodenFile.setFont(font)
        self.btnGenerateNeodenFile.setObjectName("btnGenerateNeodenFile")
        self.hQbox_1.addWidget(self.btnGenerateNeodenFile)
        spacerItem4 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.hQbox_1.addItem(spacerItem4)
        self.vQBox_main.addLayout(self.hQbox_1)
        spacerItem5 = QtWidgets.QSpacerItem(10, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.vQBox_main.addItem(spacerItem5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.btnEditDefinitions = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnEditDefinitions.setFont(font)
        self.btnEditDefinitions.setObjectName("btnEditDefinitions")
        self.horizontalLayout.addWidget(self.btnEditDefinitions)
        spacerItem7 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.vQBox_main.addLayout(self.horizontalLayout)
        spacerItem8 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.vQBox_main.addItem(spacerItem8)

        self.retranslateUi(MainWindowDialog)
        QtCore.QMetaObject.connectSlotsByName(MainWindowDialog)

    def retranslateUi(self, MainWindowDialog):
        _translate = QtCore.QCoreApplication.translate
        MainWindowDialog.setWindowTitle(_translate("MainWindowDialog", "Main Windows"))
        self.btnConvertGrb.setText(_translate("MainWindowDialog", "Convert\n"
"Geber\n"
"Files"))
        self.btnGenerateNeodenFile.setText(_translate("MainWindowDialog", "Generate\n"
"Pick and Place\n"
"File"))
        self.btnEditDefinitions.setText(_translate("MainWindowDialog", "Edit definitions"))
