M48
; DRILL file {KiCad (6.0.2)} date Tue Mar  8 21:55:42 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-08T21:55:42+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.000
%
G90
G05
T1
X114.808Y-57.658
X129.794Y-57.658
T2
X146.558Y-82.037
X146.558Y-84.577
T3
X99.06Y-58.42
X104.14Y-58.42
T0
M30
